version: '3'

services:
  gateway:
    image: rubyjobsru/gateway
    ports:
      - 8080:8080
      - 444:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/etc/traefik/acme/acme.json
      - ./.htpasswd:/etc/traefik/.htpasswd
